apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: file-share-ns
  name: file-share-deployment
  labels:
    app: file-share
spec:
  selector:
    matchLabels:
      app: file-share
  replicas: 1
  template:
    metadata:
      labels:
        app: file-share
    spec:
      containers:
        - name: file-share
          image: iamkimchi/blitzshare.fileshare.api:local-latest
          imagePullPolicy: Always
          env:
            - name: ENV
              value: prod
            - name: PORT
              value: "8000"
            - name: S3_BUCKET_NAME
              value: blitzshare-fileshare-store
            - name: S3_BUCKET_UPLOAD_KEY
              value: "share" 
            - name: S3_BUCKET_REGION
              value: "*********" 
            - name: QUEUE_URL
              value: kubemq-cluster-grpc.kubemq.svc.cluster.local
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 256Mi
              cpu: "250m"
            requests:
              memory: 128Mi
              cpu: "80m"