apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: file-share-ns
  name: file-share-deployment
  labels:
    app: file-share
spec:
  selector:
    matchLabels:
      app: file-share
  replicas: 1
  template:
    metadata:
      labels:
        app: file-share
    spec:
      containers:
        - name: file-share
          image: ${DOCKER_IMAGE_URL}
          env:
            - name: ENV
              value: "${ENV}"
            - name: PORT
              value: "${PORT}"
            - name: S3_BUCKET_NAME
              value: "${S3_BUCKET_NAME}"
            - name: S3_BUCKET_UPLOAD_KEY
              value: "${S3_BUCKET_UPLOAD_KEY}" 
            - name: S3_BUCKET_REGION
              value: "${S3_BUCKET_REGION}" 
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 256Mi
              cpu: "250m"
            requests:
              memory: 128Mi
              cpu: "80m"
