apiVersion: v1
kind: Service
metadata:
  labels:
    domain: blitzshare
  name: blitzshare-api-svc
  namespace: blitzshare-api-ns
spec:
  selector:
    app: blitzshare-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
